name: godot
version: '3.0.4'
summary: Godot Engine – Multi-platform 2D and 3D game engine
description: |
  Godot Engine is a feature-packed, cross-platform game engine to
  create 2D and 3D games from a unified interface. It provides a
  comprehensive set of common tools, so that users can focus on
  making games without having to reinvent the wheel. Games can
  be exported in one click to a number of platforms, including
  the major desktop platforms (Linux, Mac OSX, Windows) as well
  as mobile (Android, iOS) and web-based (HTML5) platforms..

confinement: strict

apps:
  godot:
    command: desktop-launch $SNAP/Godot_v3.0.4-stable_x11.64
    plugs:
      - network
      - opengl
      - desktop
      - desktop-legacy
      - x11
      - pulseaudio
      - home
      - removable-media

parts:
  godot:
    after: [desktop-glib-only]
    plugin: dump
    source: https://downloads.tuxfamily.org/godotengine/3.0.4/Godot_v3.0.4-stable_x11.64.zip
    stage-packages:
      - libgl1-mesa-dri
      - libglu1-mesa
      - libgl1-mesa-glx
      - libgles2-mesa
      - libflac8
      - libxcursor1
      - libxi6
      - libxinerama1
      - libxrandr2
      - libxrender1
      - libasound2
      - libasyncns0
      - libogg0
      - libpulse0
      - libsndfile1
      - libtheora0
      - libvorbis0a
      - libvorbisenc2
      - libvorbisfile3
      - libwebp5
    organize:
      'usr/lib/*/pulseaudio/lib*': 'lib/'
